name: deploy

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with: 
          node-version: 18.x
      - name: Build web-app
        run: |
          cd ./portfolio-eduardo
          npm ci
          npm run build
      - name: upload-files
        uses: actions/upload-artifact@v3
        with: 
          name: production-files
          path: ./portfolio-eduardo/dist
          
  Deploy:
          name: Deploy
          runs-on: ubuntu-latest
          needs: Build
          steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with: 
                name: production-files
                path: ./portfolio-eduardo/dist
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with: 
                github_token: ${{ secrets.GH_ACCESS_TOKEN }}
                publish_dir: .portfolio-eduardo/dist
                
            
