name: deploy

on:
  push:
    branches:
      - main

jobs:
  building:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
     # - name: install dependencies
        #run: |
         # cd ./portfolio-eduardo
          #rm -f yarn.lock
          #rm -f package-lock.json
          
      - name: Build web-app
        run: |
          cd ./portfolio-eduardo
          npm ci
          npm run build
      - name: upload-files
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: production-file
          path: ./dist
          
  deploy:
          name: Deploy
          runs-on: ubuntu-18.04
          needs: building
          steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with: 
                name: production-file
                path: ./dist
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with: 
                github_token: ${{ secrets.GH_ACCESS_TOKEN }}
                publish_dir: ./dist
                
            
