name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
      - name: install dependencies
        run: |
          cd ./portfolio-eduardo
          rm -f yarn.lock
          rm -f package-lock.json
          
      - name: Build web-app
        run: |
          cd ./portfolio-eduardo
          npm ci
          npm run build
